# Generated by Django 4.2.13 on 2024-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0003_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
